name: Linked List Implementatiom

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make test
    - name: Install cppcheck
      run: sudo apt-get install cppcheck
    - name: Cppcheck
      run: make analyze
    - name: Install Valgrind
      run: sudo apt-get install valgrind
    - name: Valgrind
      run: make memory_leak
    - name: clean
      run: make clean
